### ISSUE TITLE
Windows - New way of taking paths

### ISSUE THREAD

**Issue by lucassfernando** [hbisneto/FileSystemPro#33]
We can use the system's own registry keys to capture the folder path.
Here's a code I tested and it worked even after changing the name of my 'Downloads' folder:

```
import winreg

sub_key = r'SOFTWARE\\Microsoft\\Windows\\CurrentVersion\\Explorer\\Shell Folders'
download_folder_path = '{374DE290-123F-4565-9164-39C4925E467B}'
with winreg.OpenKey(winreg.HKEY_CURRENT_USER, sub_key) as key:
    location_path = winreg.QueryValueEx(key, download_folder_path)[0]

print(location_path)
```
**Note that I changed my folder name and it was still able to capture**

![image](https://github.com/hbisneto/FileSystemPro/assets/89320727/3ff3b37c-eb49-4a68-969a-4a50726d9982)

Here at this link we get a list of registry keys for the folders: [https://gist.github.com/mkropat/7550097](url)

**Comment by hbisneto** [comment]
> We can use the system's own registry keys to capture the folder path.
> Here's a code I tested and it worked even after changing the name of my 'Downloads' folder:
> 
> 
> 
> ```
> import winreg
> 
> sub_key = r'SOFTWARE\\Microsoft\\Windows\\CurrentVersion\\Explorer\\Shell Folders'
> download_folder_path = '{374DE290-123F-4565-9164-39C4925E467B}'
> with winreg.OpenKey(winreg.HKEY_CURRENT_USER, sub_key) as key:
>     location_path = winreg.QueryValueEx(key, download_folder_path)[0]
> 
> print(location_path)
> ```
> **Note that I changed my folder name and it was still able to capture**
> 
> ![image](https://github.com/hbisneto/FileSystemPro/assets/89320727/3ff3b37c-eb49-4a68-969a-4a50726d9982)
> 
> Here at this link we get a list of registry keys for the folders: [https://gist.github.com/mkropat/7550097](url)
> 

Lucas, I appreciate your comment and your implementation test is already published on the latest version of FileSystemPro. Thank you for your feedback. Thanks to you, now users can change the directory names like "Documents", "Downloads" and even yet have access to these directories.

I'm closing this issue as completed.

Once again: Thank you!

Heitor Bisneto.
